version: '2'
services:
  permissionmanagement-db:
    image: mysql:8
    # volumes:
    #     - ~/volumes/Refpoint/refauth/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=permissionmanagementdb

    ports:
      - 3308:3306
    expose:
      - 3308
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

