server:
  servlet:
    context-path:  /permission/api/v1/

logging:
  level:
    ROOT: ERROR
    com.yapikredi.permision: ERROR
    org.springframework.web: ERROR

management:
  endpoints:
    web:
      exposure:
        include=*:
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
    include:
      - swagger

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #url: jdbc:h2:~/permissionmanagementdb;DB_CLOSE_ON_EXIT=FALSE
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/permissionmanagementdb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:ykb}
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: org.hibernate.dialect.MySQL57Dialect
    data: classpath:/db/data/import.sql


    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    open-in-view : false
    hibernate:
      ddl-auto: update

      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.hbm2ddl.import_files: classpath:db/data/import.sql
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.generate_statistics: false
      hibernate:jdbc.time_zone: UTC

  # hibernate.naming.p


  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true

  jackson:
    serialization:
      indent-output: true


