server:
  servlet:
    context-path: /permission/api/v1/

logging:
  level:
    ROOT: DEBUG
    com.yapikredi.permision: DEBUG

spring:
  profiles:
    active: dev
    include:
      - swagger

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:~/permissionmanagementdb;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:h2:mem:permissionmanagementdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name:
    platform: h2
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true



  #  datasource:
  #    driverClassName: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3308/permissionmanagementdb
  #    username: root
  #    password: ykb

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming

  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev,faker

  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true

  jackson:
    serialization:
      indent-output: true

permission:
  advanceDayUseFirstYear: 10

